version: '3.8'

services:
  self-healing:
    container_name: self-healing-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"  # Expose metrics endpoint
    environment:
      - ERROR_THRESHOLD=100
      - WARNING_THRESHOLD=500
    volumes:
      - .:/app  # Mount entire current dir to ensure live sync of code
    depends_on:
      - prometheus
      - grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge
