global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  # Self-Healing System Metrics
  - job_name: 'self-healing'
    static_configs:
      - targets: ['self-healing-container:8000']

  # Kubernetes Node Monitoring
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_name]
        action: replace
        target_label: node

  # Kubernetes Pod Monitoring
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod

  # Kube-State-Metrics (for Kubernetes object state)
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

  # Kubelet (collects node-level metrics)
  - job_name: 'kubelet'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_name]
        action: replace
        target_label: node

  # Node Exporter (for host system metrics)
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
        action: keep
        regex: prometheus-node-exporter;kube-system

  # Prometheus System Metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker Container Monitoring
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
